language: node_js

node_js:
- 14

script: make publish

env:
  global: 
    #NPM_TOKEN=...
    - secure: Ywb7xkaARTcNzQZ71xAlft18JIkBupwSWkxuGvd7ajM8oiYRu9CWWZEqdaKZxhbC8EqAEGWLcRaYKXJehhCBPlGEbbVt5mkxrOGqp+6o4hOYyZQN0XaYPLV81KikeoWlOreR/VVgjbDWsgq6gVLI5jY64DDYopnntrj9ExP/SArMii+WWsq3HZQ3rtjasnH/TEU3451JTcxlY984xBMr8Jju/Q3KwWWzkG3zhUJWbXCpvJWR6q9idpBEUim1JNMjRtKW2v77mylPvYfRWPsJ58ZCnsf/U+KJp9QHeP71f++V6ebZiU06AS+xH3F+jNzmFnJlDaqpy/VpsbszvFH9VXjK/Y1qawDSYmn9sONUhTDdl6k+dZjD1j2S0d9+Q7G0M+1KLyXV5Iw4iyhuXyircnJIqlAtRXnedS5knyCmqbETWXlK4mPWHkyXPbQrsBnnJ4rGDg22eM71KVU/tZcLpbBUL+kFE7q5vKD4nkfM4H9OXJVlWLn9nrSV95JmC9jIpldg31gcyVXBH5Vo+QFL5R3tP0pN34HA+gGdD6hXPN8MddZOztdZC7edHD+padTj+Ld3PvNcG6J6fmvfltLVjx6LWbUpOVJ8gGuMA/w3oKudtCeO6+5hIqraH4LLI3sPph6anGAPAzd3o9wZ38u554jOCP+T2AXRmVGfTdN4www=
